"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[➜](bold #b8bb26)"
error_symbol = "[➜](bold #fb4934)"

[aws]
symbol = " "
style = "#fe8019"

[buf]
symbol = " "
style = "#8ec07c"

[bun]
symbol = " "
style = "#fb4934"

[c]
symbol = " "
style = "#83a598"

[cpp]
symbol = " "
style = "#83a598"

[cmake]
symbol = " "
style = "#928374"

[conda]
symbol = " "
style = "#b8bb26"

[crystal]
symbol = " "
style = "#fb4934"

[dart]
symbol = " "
style = "#83a598"

[deno]
symbol = " "
style = "#b8bb26"

[directory]
read_only = " 󰌾"
style = "bold #83a598"

[docker_context]
symbol = " "
style = "#83a598"

[elixir]
symbol = " "
style = "#d3869b"

[elm]
symbol = " "
style = "#8ec07c"

[fennel]
symbol = " "
style = "#fabd2f"

[fortran]
symbol = " "
style = "#d3869b"

[fossil_branch]
symbol = " "
style = "#d3869b"

[gcloud]
symbol = " "
style = "#83a598"

[git_branch]
symbol = " "
style = "bold #d3869b"

[git_commit]
tag_symbol = '  '
style = "#fe8019"

[golang]
symbol = " "
style = "#8ec07c"

[gradle]
symbol = " "
style = "#83a598"

[guix_shell]
symbol = " "
style = "#fabd2f"

[haskell]
symbol = " "
style = "#d3869b"

[haxe]
symbol = " "
style = "#fe8019"

[hg_branch]
symbol = " "
style = "#d3869b"

[hostname]
ssh_symbol = " "
style = "bold #fe8019"

[java]
symbol = " "
style = "#fb4934"

[julia]
symbol = " "
style = "#d3869b"

[kotlin]
symbol = " "
style = "#d3869b"

[lua]
symbol = " "
style = "#83a598"

[memory_usage]
symbol = "󰍛 "
style = "bold #d3869b"

[meson]
symbol = "󰔷 "
style = "#b8bb26"

[nim]
symbol = "󰆥 "
style = "#fabd2f"

[nix_shell]
symbol = " "
style = "#83a598"

[nodejs]
symbol = " "
style = "#b8bb26"

[ocaml]
symbol = " "
style = "#fe8019"

[os]
disabled = false
style = "#928374"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
#fb4934 = " "
#fb4934 = " "
RockyLinux = " "
#fb4934 = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[package]
symbol = "󰏗 "
style = "#fe8019"

[perl]
symbol = " "
style = "#83a598"

[php]
symbol = " "
style = "#d3869b"

[pijul_channel]
symbol = " "
style = "#d3869b"

[pixi]
symbol = "󰏗 "
style = "#fabd2f"

[python]
symbol = " "
style = "#fabd2f"

[rlang]
symbol = "󰟔 "
style = "#83a598"

[ruby]
symbol = " "
style = "#fb4934"

[rust]
symbol = "󱘗 "
style = "#fe8019"

[scala]
symbol = " "
style = "#fb4934"

[status]
symbol = " "
style = "#fb4934"

[swift]
symbol = " "
style = "#fe8019"

[xmake]
symbol = " "
style = "#fabd2f"

[zig]
symbol = " "
style = "#fabd2f"
