hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway DISPLAY && sleep 1 && systemctl --user start xdg-desktop-portal-gtk xdg-desktop-portal")
    hl.exec_cmd("waybar")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("copyq --start-server")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("/usr/lib/gcr-ssh-agent")
    hl.exec_cmd("swayidle -w before-sleep 'swaylock -f'")
end)
