########################
### AUTOSTART
########################

exec-once=waybar
exec-once=awww-daemon
exec-once=copyq --start-server
exec-once=gnome-keyring-daemon --start --components=secrets
exec-once=/usr/lib/gcr-ssh-agent
exec-once=swayidle -w before-sleep 'swaylock -f'

########################
### INPUT
########################

disable_while_typing=1
tap_to_click=1
trackpad_natural_scrolling=1
middle_button_emulation=1

########################
### INCLUDE FILES
########################

source=./theme.conf
source=./keybinds.conf
