########################
### AUTOSTART
########################

exec-once=waybar
exec-once=awww-daemon
exec-once=copyq --start-server
exec-once=gnome-keyring-daemon --start --components=secrets
exec-once=/usr/lib/gcr-ssh-agent
exec-once=swayidle -w before-sleep 'swaylock -f'

# For screen recording
exec-once = systemctl --user restart xdg-desktop-portal-wlr xdg-desktop-portal

########################
### INPUT
########################

disable_while_typing=1
tap_to_click=1
trackpad_natural_scrolling=1
middle_button_emulation=1
accel_speed=-0.9
repeat_delay=250
sloppy_focus=0

########################
### MONITORS
########################

# AOC 27G4 - main monitor (primary, 180Hz)
monitorrule=name:DP-1,width:1920,height:1080,refresh:180,x:1920,y:0,scale:1,vrr:1,rr:0

# Samsung S24C650 - second monitor
monitorrule=name:DP-2,width:1920,height:1080,refresh:60,x:0,y:0,scale:1,vrr:0,rr:0

# Allow focus to move across monitors
focus_cross_monitor=1

# Set default tags for each monitor
# Main monitor
tagrule=id:1,monitor_name:DP-1,no_hide:1,layout_name:tgmix
tagrule=id:2,monitor_name:DP-1,no_hide:1,layout_name:tgmix
tagrule=id:3,monitor_name:DP-1,no_hide:1,layout_name:tgmix
tagrule=id:4,monitor_name:DP-1,no_hide:1,layout_name:tgmix
tagrule=id:5,monitor_name:DP-1,no_hide:1,layout_name:tgmix
# Second monitor
tagrule=id:6,monitor_name:DP-2,no_hide:1,layout_name:tgmix
tagrule=id:7,monitor_name:DP-2,no_hide:1,layout_name:tgmix
tagrule=id:8,monitor_name:DP-2,no_hide:1,layout_name:tgmix
tagrule=id:9,monitor_name:DP-2,no_hide:1,layout_name:tgmix

########################
### INCLUDE FILES
########################

source=./theme.conf
source=./keybinds.conf
source=./layouts.conf
