########################
### GENERAL LOOK & FEEL
########################

# Gaps
gappih=6
gappiv=6
gappoh=6
gappov=6

smartgaps=0

borderpx=2
border_radius=6
no_radius_when_single=1

blur=1
blur_layer=1
focused_opacity=0.8
unfocused_opacity=0.8

########################
### COLORS
########################

# Mango expects colors as 0xRRGGBBAA.
focuscolor=0xEFD24DFF
bordercolor=0x374D70FF
rootcolor=0x374D70FF

urgentcolor=0x374D70FF
scratchpadcolor=0x374D70FF
globalcolor=0x374D70FF
overlaycolor=0x374D70FF

########################
### CURSOR
########################

cursor_theme=Bibata_Spirit
cursor_size=32

########################
### ANIMATIONS
########################

animation_type_open=zoom
animation_type_close=zoom

animation_duration_move=250
animation_duration_open=250
animation_duration_focus=25
