# vim:fileencoding=utf-8:foldmethod=marker

font_family      JetbrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14.0

window_padding_width 10
cursor #a5c2f0
cursor_text_color #111111

cursor_shape block
cursor_shape_unfocused hollow
shell_integration no-cursor

#: The thickness of the underline cursor (in pts).

cursor_blink_interval 0

# cursor_trail 1
# cursor_trail_color none

scrollback_lines 2000

scrollbar scrolled-and-hovered
scrollbar_interactive yes
scrollbar_jump_on_click yes
scrollbar_width 0.5
scrollbar_hover_width 1
scrollbar_hitbox_expansion 0.5

scrollbar_handle_color foreground
scrollbar_track_color foreground

mouse_hide_wait 3.0

# url_color #0087bd
# url_style curly

open_url_with default firefox
show_hyperlink_targets yes
underline_hyperlinks always

clear_selection_on_clipboard_loss no
strip_trailing_spaces always

select_by_word_characters @-./_~?&=%+#
select_by_word_characters_forward

tab_bar_edge top

tab_bar_margin_width 5.0
tab_bar_margin_height 2.0 2.0
tab_bar_style slant

tab_bar_align left
tab_bar_min_tabs 2
tab_switch_strategy previous

# active_tab_foreground   #000
# active_tab_background   #eee
# active_tab_font_style   bold-italic
# inactive_tab_foreground #444
# inactive_tab_background #999
# inactive_tab_font_style normal

# tab_bar_background none
# tab_bar_margin_color none

foreground #a5c2f0
background #000000
background_opacity 0.5
background_blur 1
