general {
    lock_cmd = hyprlock
    idle_timeout = 600   # seconds until lock
    sleep_timeout = 900  # seconds until suspend
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
}
